"""Implemente the Article model

Revision ID: 7b11c2e0ccd1
Revises: 
Create Date: 2024-11-23 20:09:53.154014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b11c2e0ccd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Enum('BASIC', 'INTERMEDIATE', 'ADVANCED', name='articlelevel'), nullable=False),
    sa.Column('taxonomy', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('research_prompt', sa.Text(), nullable=True),
    sa.Column('research_result', sa.Text(), nullable=True),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.Column('generation_started_at', sa.DateTime(), nullable=True),
    sa.Column('last_generation_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('article_relationships',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('related_article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['related_article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'related_article_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_relationships')
    op.drop_table('articles')
    # ### end Alembic commands ###
