"""add word count to articles

Revision ID: a1fc5a258bde
Revises: 7b11c2e0ccd1
Create Date: 2024-11-24 21:21:20.518788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1fc5a258bde'
down_revision = '7b11c2e0ccd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('word_count', sa.Integer(), nullable=True))
    
    # Update existing articles with word count
    op.execute("""
        UPDATE articles 
        SET word_count = COALESCE(
            array_length(regexp_split_to_array(content, '\s+'), 1), 0)
    """)
 
    # Make it non-nullable after populating
    op.alter_column('articles', 'word_count',
                    existing_type=sa.Integer(),
                    nullable=False,
                    server_default='0')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('word_count')

    # ### end Alembic commands ###
