"""add relevance_score to articles

Revision ID: cd9b9b6cd84b
Revises: 7e36533302d4
Create Date: 2024-11-25 05:55:08.922325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cd9b9b6cd84b"
down_revision = "7e36533302d4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("articles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("relevance_score", sa.Float(), nullable=True))

    op.execute("UPDATE articles SET relevance_score = 0")

    op.alter_column(
        "articles", "relevance_score", existing_type=sa.Float(), nullable=False
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("articles", schema=None) as batch_op:
        batch_op.drop_column("relevance_score")

    # ### end Alembic commands ###
